// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANN9udeo9HW-VUpBYVmMt6z4auaACn6w8',
    appId: '1:741455581644:web:c15ad9d84b424a379e0d69',
    messagingSenderId: '741455581644',
    projectId: 'iti-project-16804',
    authDomain: 'iti-project-16804.firebaseapp.com',
    storageBucket: 'iti-project-16804.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHn9KFUW9haKufopQBDzrFwJAYia6Xlo',
    appId: '1:741455581644:android:36d9f7103a3a99ff9e0d69',
    messagingSenderId: '741455581644',
    projectId: 'iti-project-16804',
    storageBucket: 'iti-project-16804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv9FT_UpRvG2nk1SGtvSDz4VixNZPTm2c',
    appId: '1:741455581644:ios:23b0aef23d04b5c19e0d69',
    messagingSenderId: '741455581644',
    projectId: 'iti-project-16804',
    storageBucket: 'iti-project-16804.appspot.com',
    iosClientId: '741455581644-lrs1f32uof89fg1oparac929rbefcjnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv9FT_UpRvG2nk1SGtvSDz4VixNZPTm2c',
    appId: '1:741455581644:ios:23b0aef23d04b5c19e0d69',
    messagingSenderId: '741455581644',
    projectId: 'iti-project-16804',
    storageBucket: 'iti-project-16804.appspot.com',
    iosClientId: '741455581644-lrs1f32uof89fg1oparac929rbefcjnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiProject',
  );
}
